### ISSUE TITLE
扫码后网页没有反应

### ISSUE THREAD

**Issue by anyhui** [cdle/xdd#1]
京东扫码后网页没有反应，不会跳转到相应的页面。刚刚拉库编译的版本。arm64.

**Comment by 764763903a** [comment]
UA过期自行更换UA

**Comment by yemingjkl** [comment]
> UA过期自行更换UA

如何更换UA呀

**Comment by Ph4nt0m-JSK** [comment]
![image](https://user-images.githubusercontent.com/37372637/129547075-361080b4-bbef-4f3f-8d68-afeccc5ebd7a.png)

**Comment by anyhui** [comment]
![image](https://user-images.githubusercontent.com/22373947/129550964-4460f0d9-5393-421b-87d4-37e47a194fa1.png)
设置了自定义UA，扫码确认登录，页面的二维码会更换，后台报错。不能跳转页面。
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by wanghlstar** [comment]
内网穿透后，扫码报这个错~~{1 264 出错了，请退出重试}
局域网不报错~~
