### ISSUE TITLE
怎么编译？有教程吗？

### ISSUE THREAD

**Issue by sjkhsl** [cdle/xdd#16]
怎么编译？有教程吗？

**Comment by wanghlstar** [comment]
百度一下~  go 编译
amd64的 比较好编译，直接 go build 
arm64 参考

CC=aarch64-linux-gnu-gcc-5 CXX=aarch64-linux-gnu-g++-5 GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -ldflags '-linkmode "external" -extldflags "-static"'
