### ISSUE TITLE
查询指令提示权限不足

### ISSUE THREAD

**Issue by xiaotian1339** [cdle/xdd#17]
只有配置文件里qquid写的qq可以查询，其他都无法查询，查不到自己的，也查不到其他人的。
可以查自己的也行，但是自己查自己的还是会提示 你的权限不足

**Comment by wanghlstar** [comment]
发送 查询  会返回当前绑定的 发送qq号的 相关jdh号xin'xi ~

**Comment by xiaotian1339** [comment]
> 发送 查询 会返回当前绑定的 发送qq号的 相关jdh号xin'xi ~

试过了，一发送就是  你的权限不足

**Comment by xiaotian1339** [comment]
> 发送 查询 会返回当前绑定的 发送qq号的 相关jdh号xin'xi ~

谢谢了   怪不得  之前发的查询 N  提示不足  直接发查询就可以了
