### ISSUE TITLE
XDD无法编译

### ISSUE THREAD

**Issue by sherlockQvQ** [cdle/xdd#7]
go: github.com/Baozisoftware/qrcode-terminal-go@v0.0.0-20170407111555-c0650d8dff0f: Get "https://proxy.golang.org/github.com/%21baozisoftware/qrcode-terminal-go/@v/v0.0.0-20170407111555-c0650d8dff0f.mod": dial tcp 142.250.204.81:443: i/o timeout

试了多台服务器一直出现这个问题

**Comment by wanghlstar** [comment]
加代理~~ 
go env -w GOPROXY="https://goproxy.cn,direct"

**Comment by sherlockQvQ** [comment]
> 加代理~~
> go env -w GOPROXY="https://goproxy.cn,direct"

还有一个问题，有时候xdd会莫名杀进程，然后我重启xdd后，发现网页被恢复原样，因为我给xdd做了重做一个网页欢迎界面，问题就会很明显的出来了
