### ISSUE TITLE
大佬您好，青龙2.8.3用xdd会把变量的备注都删了

### ISSUE THREAD

**Issue by prcxu** [cdle/xdd#9]
大佬您好
青龙2.8.3用xdd会把变量的备注都删了

xdd检测到过期ck都是直接删除，能否失效禁用或删除 给个变量接口可以选 ,扫码后自动启用

xdd首次启动会读取青龙env生成数据库，后续启动会用xdd的数据库覆盖青龙env,这样如果xdd掉了后台，这个期间加了ck xdd启动会把新增的ck搞没

xdd能否容器内启动，最好能跟随容器启动

进入管理面板的当时能否加个管理员通道

个人使用一点体验(意淫意淫)，大佬看过就算，勿喷😂

**Comment by wanghlstar** [comment]
我的xdd在容器内~~~你加个extra脚本启动下

**Comment by prcxu** [comment]
> 我的xdd在容器内~~~你加个extra脚本启动下

好的谢谢

**Comment by buhonghao** [comment]
为什么我的启动读完青龙env后，会把env里面的ck全部删掉？

**Comment by prcxu** [comment]
> 为什么我的启动读完青龙env后，会把env里面的ck全部删掉？

这个没遇到

**Comment by buhonghao** [comment]
请问容器内运行的命令是什么，我放到容器内运行竟然提示不存在这个文件。根据你提到的读取-覆盖流程，我估计ck被清空是读取env后清空但是没有权限回写吧。

**Comment by wanghlstar** [comment]
> 请问容器内运行的命令是什么，我放到容器内运行竟然提示不存在这个文件。根据你提到的读取-覆盖流程，我估计ck被清空是读取env后清空但是没有权限回写吧。

版本不对吧~  alpine 需要用 arm版本， 去拉取个 xgo 的镜像，
把库编译进去，不然会动态库找不到起不来
CC=aarch64-linux-gnu-gcc-5 CXX=aarch64-linux-gnu-g++-5 GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -ldflags '-linkmode "external" -extldflags "-static"'
